### ISSUE TITLE
runserver

### ISSUE THREAD

**Issue by ayourr** [mrb75/advertising#1]
Hello 
how to run the project ? 
can you share your .env file , did you use postgresql ?
 

localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connection

thanks 
[readme.md](https://github.com/mrb75/advertising/files/10506309/readme.md)

**Comment by mrb75** [comment]
Hi 
thank you for your question. 
You can create a ".env" file and put the value that is mentioned below in it:
```

DEBUG=True
SECRET_KEY=******
DB_HOST=***
DB_USER=postgres
DB_NAME=***
DB_PORT=5432
DB_PASSWORD=***
CELERY_BROKER_URL=<< rabbitmq server url >>
CELERY_RESULT_BACKEND=<< redis server url >>

```


These variables are for postgresql database. You can use other databases by changing this file and changing database to the "setting.py" file in the project.
